name: KTB 해커톤 14조 PR CI 파이프라인

on:
  pull_request:
    branches: [ "develop"]

jobs:

  test:
    runs-on: ubuntu-22.04
    if: success()
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: 파이썬 의존성 설치
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.19"

      - name: 의존성 설치
        run: pip install -r requirements.txt

      - name: Ruff 문법 오류 코드 검사
        run: ruff check .

  notify-discord:
    runs-on: ubuntu-22.04
    needs: test
    if: always()
    steps:
      - name: Discord 빌드 알림
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_AI_PR_URL }}
          title: "${{ needs.build.result == 'success' && '✅' || '❌' }} 새로운 PR이 올라왔습니다!"
          description: |
            **제목**: ${{ github.event.pull_request.title }}
            **작성자**: ${{ github.event.pull_request.user.login }}
            **브랜치**: `${{ github.event.pull_request.base.ref }}`←`${{ github.event.pull_request.head.ref }}`

            **📊 빌드 결과**:
            - 상태: ${{ needs.build.result == 'success' && '성공' || '실패' }}

            **🔗 링크**:
            - [PR 확인하기](${{ github.event.pull_request.html_url }})

          color: "${{ needs.build.result == 'success' && 65280 || 16711680 }}"
          username: GitHub PR Bot
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png